language: ruby
cache:
  bundler: true
  directories:
    - $HOME/vendor/bundle/
    - $HOME/.rvm/

rvm:
  - 2.0.0-p648
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - 2.6.0

branches:
  only:
    - master
    - develop

env:
  global:
    - RUBYGEMS_API_KEY="ADD_ENCRYPTED_ENV_VAR_KEY"

before_install:
  - curl http://curl.haxx.se/ca/cacert.pem -o /usr/local/share/cacert.pem
  - source ~/.rvm/scripts/rvm
  # There is a bug in travis. When using system ruby, bundler is not
  # installed and causes the default install action to fail.
  - if [ "$TRAVIS_RUBY_VERSION" = "system" ]; then sudo gem install "bundler:~> 1.17.0"; else gem install "bundler:~> 1.17.0"; fi

jobs:
  include:
    - &test
      stage: test
      name: Ruby 2.5.1
      rvm: 2.5.1
      script:
        - bundle exec rspec

    - stage: deploy
      name: Deploy Synx to rubygems
      rvm: 2.5.1
      script: echo "Deploying to ruby rubygems..."
      # deploy:
      #   provider: rubygems
      #   gem: synx
      #   api_key: $RUBYGEMS_API_KEY
      #   on: deploy-gem-release

stages:
  - test
  - deploy
    if: "branch = master OR (commit_message =~ /(@deploy synx)/) AND (type != pull_request)"
